M2DM-project/M2DM.ver2.0

build.gradle
src/main/java/ddwu/project/mdm_ver2/config/SwaggerConfig.java
src/main/resources/application.yml

> feat : springdoc-swagger 설정
어떤 변경 사항이 있나요?
- http://localhost:8080/swagger-ui/index.html
**Springfox vs Springdoc**
`Springfox`에서는 api 간 정렬이 되지 않는다. springfox는 더 이상 업데이트를 하지 않는다.
`Springdoc`에서는 properties 파일을 이용해서 그룹 간, api 간 정렬이 가능하다. (abc순, method순)

feat : springdoc-swagger 설정

---

src/main/java/ddwu/project/mdm_ver2/contorller/product/ProductForm.java
src/main/java/ddwu/project/mdm_ver2/contorller/product/ProductFormController.java
src/main/java/ddwu/project/mdm_ver2/contorller/product/ViewProductController.java
src/main/java/ddwu/project/mdm_ver2/dao/ProductDao.java
src/main/java/ddwu/project/mdm_ver2/domain/Product.java
src/main/java/ddwu/project/mdm_ver2/domain/User.java
src/main/java/ddwu/project/mdm_ver2/service/product/ProductFacade.java
src/main/java/ddwu/project/mdm_ver2/service/product/ProductFormValidator.java
src/main/java/ddwu/project/mdm_ver2/service/product/ProductService.java

feat : Proudct 구현

---

src/main/java/ddwu/project/mdm_ver2/contorller/product/AddProductController.java
src/main/java/ddwu/project/mdm_ver2/contorller/product/ViewProductController.java
src/main/java/ddwu/project/mdm_ver2/dao/ProductDao.java
src/main/java/ddwu/project/mdm_ver2/domain/Brand.java
src/main/java/ddwu/project/mdm_ver2/domain/Category.java
src/main/java/ddwu/project/mdm_ver2/domain/Product.java
src/main/java/ddwu/project/mdm_ver2/domain/User.java
src/main/java/ddwu/project/mdm_ver2/service/product/ProductFacade.java
src/main/java/ddwu/project/mdm_ver2/service/product/ProductService.java

feat : Brand/Category DB
> ver1.0 int BrandCode, CategoryCode 
ver2.0 String BrandCode, CategoryCode 
어떤 변경 사항이 있나요?

feat : Brand/Category DB

---

src/main/java/ddwu/project/mdm_ver2/dao/CategoryDao.java
src/main/java/ddwu/project/mdm_ver2/domain/Category.java
src/main/java/ddwu/project/mdm_ver2/service/category/CategoryService.java

> Category DB 초기값 지정
어떤 변경 사항이 있나요?

feat : Category 초기값

---

build.gradle
src/main/java/ddwu/project/mdm_ver2/KakaoController.java
src/main/webapp/WEB-INF/jsp/stateService.jsp
src/main/webapp/WEB-INF/jsp/test.jsp

🔸 jsp 화면 찾지 못함 --> application.yml / prifix, suffix 추가
🔸 실행 시 ionShutdownHook 에러
--> build.gradle >> 
implementation 'org.apache.tomcat.embed:tomcat-embed-jasper' 
implementation group: 'org.glassfish.web', name: 'jakarta.servlet.jsp.jstl', version: `'2.0.0'`
어떤 변경 사항이 있나요?
- [✔] 새로운 기능 추가
- [✔] 버그 수정

feat : kakao login

---

src/main/java/ddwu/project/mdm_ver2/repository/BrandRepository.java
src/main/java/ddwu/project/mdm_ver2/repository/CategoryRepository.java
src/main/java/ddwu/project/mdm_ver2/service/BrandService.java
src/main/java/ddwu/project/mdm_ver2/service/CategoryService.java

> fix : Brand, Category 초기값
어떤 변경 사항이 있나요?
초기값이 DB에 들어갔는데 실행을 통해 들어가게 된다면 무결성 제약 조건 위배

fix : Brand, Category 초기값

---

src/main/java/ddwu/project/mdm_ver2/contorller/ProductController.java
src/main/java/ddwu/project/mdm_ver2/repository/ProductRepository.java
src/main/java/ddwu/project/mdm_ver2/service/ProductService.java

> feat : 상품 정렬(가격순, 등록순)
어떤 변경 사항이 있나요?

feat : 상품 정렬(가격순, 등록순)

---

src/main/java/ddwu/project/mdm_ver2/contorller/ProductController.java
src/main/java/ddwu/project/mdm_ver2/repository/ProductRepository.java
src/main/java/ddwu/project/mdm_ver2/service/ProductService.java

> [FEATURE] 상품 정렬
어떤 변경 사항이 있나요?
[상품 정렬]
sortBy에
**lowprice(낮은가격순),highprice(높은 가격순), newest(등록순)  입력 가능**
cateCode에
**FUR, FAB, AD, STO, DEC, LIT, PLA 입력 가능**
```
1. sortBy , cateCode 값 다 안 들어오면 기본 list출력
2. sortBy값 들어오고 ,cateCode값 안 들어오면 카테고리 분류 안하고 정렬
3. sortBy, cateCode 값 다 들어오면 카테고리 분류 후 정렬
```

✨ [FEATURE] 상품 정렬

---

src/main/java/ddwu/project/mdm_ver2/contorller/HomeController.java
src/main/java/ddwu/project/mdm_ver2/contorller/KakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/User.java
src/main/java/ddwu/project/mdm_ver2/repository/UserRepository.java
src/main/java/ddwu/project/mdm_ver2/service/KakaoService.java
src/main/webapp/WEB-INF/jsp/setNickname.jsp
src/main/webapp/WEB-INF/jsp/test.jsp

회원 탈퇴 기능 추가
service-repository
어떤 변경 사항이 있나요?

feat: 회원탈퇴, annotation 수정

---

src/main/java/ddwu/project/mdm_ver2/contorller/HomeController.java
src/main/java/ddwu/project/mdm_ver2/contorller/KakaoController.java

swagger 연동 위한 annotation 수정
어떤 변경 사항이 있나요?

feat: swagger 연동

---

src/main/java/ddwu/project/mdm_ver2/contorller/ProductController.java
src/main/java/ddwu/project/mdm_ver2/repository/ProductRepository.java
src/main/java/ddwu/project/mdm_ver2/service/ProductService.java

> ✨ [FEATURE] 상품 등록 개수
어떤 변경 사항이 있나요?
상품 개수
cateCode값
**빈값** 
: 전체 상품 개수
**FUR, FAB, AD, STO, DEC, LIT, PLA 입력** 
: 카테고리 분류 후 상품 개수

✨ [FEATURE] 상품 등록 개수

---

src/main/java/ddwu/project/mdm_ver2/contorller/ProductController.java
src/main/java/ddwu/project/mdm_ver2/domain/Product.java
src/main/java/ddwu/project/mdm_ver2/repository/ProductRepository.java
src/main/java/ddwu/project/mdm_ver2/service/ProductService.java

> ✨ feat : 제품이름 기준 상품 검색
**상품검색**
제품이름(name)기준 포함된 문자열 출력
어떤 변경 사항이 있나요?

✨ feat : 제품이름 기준 상품 검색

---

src/main/java/ddwu/project/mdm_ver2/contorller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/contorller/ViewKakaoController.java
src/main/java/ddwu/project/mdm_ver2/repository/UserRepository.java
src/main/java/ddwu/project/mdm_ver2/service/KakaoService.java
src/main/java/ddwu/project/mdm_ver2/validator/AbstractValidator.java
src/main/java/ddwu/project/mdm_ver2/validator/CheckNicknameValidator.java

신규 회원 가입 시 닉네임 중복 검사
어떤 변경 사항이 있나요?

feat: 닉네임 중복 검사

---

src/main/java/ddwu/project/mdm_ver2/contorller/FavoriteController.java
src/main/java/ddwu/project/mdm_ver2/domain/Favorite.java
src/main/java/ddwu/project/mdm_ver2/repository/FavoriteRepository.java
src/main/java/ddwu/project/mdm_ver2/service/FavoriteService.java

찜 API 기능 추가
- 상품 찜 -> 찜 데이터 추가
- 상품 찜 해제 -> 찜 데이터 삭제
- 
어떤 변경 사항이 있나요?

feat: 상품 찜 기능

---

src/main/java/ddwu/project/mdm_ver2/contorller/CartController.java
src/main/java/ddwu/project/mdm_ver2/contorller/CartItemController.java
src/main/java/ddwu/project/mdm_ver2/domain/Cart.java
src/main/java/ddwu/project/mdm_ver2/domain/CartItem.java
src/main/java/ddwu/project/mdm_ver2/domain/Product.java
src/main/java/ddwu/project/mdm_ver2/dto/CartResponse.java
src/main/java/ddwu/project/mdm_ver2/repository/CartItemRepository.java
src/main/java/ddwu/project/mdm_ver2/repository/CartRepository.java
src/main/java/ddwu/project/mdm_ver2/repository/UserRepository.java
src/main/java/ddwu/project/mdm_ver2/service/CartItemService.java
src/main/java/ddwu/project/mdm_ver2/service/CartService.java
src/main/java/ddwu/project/mdm_ver2/service/ProductService.java

> ✨ feat : 장바구니 기능(프레임 생성)
어떤 변경 사항이 있나요?
Cart, CartItem DB생성
변경 사항에 대한 테스트를 안했습니다.(버그 수정/기능에 대한 테스트).
유저, 상품 수정사항 있어서 미완성으로 올립니다.

✨ feat : 장바구니 기능(프레임 생성)

---

src/main/java/ddwu/project/mdm_ver2/contorller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/contorller/ViewKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/User.java
src/main/java/ddwu/project/mdm_ver2/repository/UserRepository.java
src/main/java/ddwu/project/mdm_ver2/service/KakaoService.java
src/main/webapp/WEB-INF/jsp/test.jsp

- kakaoService 오류 -> 삭제된 method 추가
- user domain -> userRole 삭제, oracle db 등록 시 기본 값으로 저장
어떤 변경 사항이 있나요?

feat: kakaoService 오류 수정, user domain 수정

---

src/main/java/ddwu/project/mdm_ver2/contorller/CartController.java
src/main/java/ddwu/project/mdm_ver2/contorller/CartItemController.java
src/main/java/ddwu/project/mdm_ver2/domain/Cart.java
src/main/java/ddwu/project/mdm_ver2/domain/CartItem.java
src/main/java/ddwu/project/mdm_ver2/domain/User.java
src/main/java/ddwu/project/mdm_ver2/service/CartItemService.java
src/main/java/ddwu/project/mdm_ver2/service/CartService.java

> ✨ feat : 장바구니품목 추가
추가하면 수량,가격도 반영
어떤 변경 사항이 있나요?
유저DB 바뀌면 코드 수정될 것 같음.

✨ feat : 장바구니품목 추가

---

src/main/java/ddwu/project/mdm_ver2/contorller/CartController.java
src/main/java/ddwu/project/mdm_ver2/contorller/CartItemController.java
src/main/java/ddwu/project/mdm_ver2/domain/Cart.java
src/main/java/ddwu/project/mdm_ver2/domain/CartItem.java
src/main/java/ddwu/project/mdm_ver2/domain/Product.java
src/main/java/ddwu/project/mdm_ver2/service/CartItemService.java
src/main/java/ddwu/project/mdm_ver2/service/CartService.java

> ✨ feat : 장바구니API
어떤 변경 사항이 있나요?
**결과**
"cartCount": 전체수량,
"cartPrice": 전체가격.
"cartItemCount": 장바구니 안의 품목 수량,
"cartItemPrice": 장바구니 안의 품목 가격
해당하는품목 수량,가격 변화 + 전체수량,가격 변화
cartitemlds : 장바구니항목id
‼️casecade영속성 관계 부족한 부분이 있을 수 있습니다.
‼️유저부분 session->token으로 변경되어 ,유저api완성되면 장바구니api수정할 예정입니다.

✨ feat : 장바구니API

---

build.gradle
src/main/java/ddwu/project/mdm_ver2/contorller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/contorller/ViewKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/User.java
src/main/java/ddwu/project/mdm_ver2/dto/UserDTO.java
src/main/java/ddwu/project/mdm_ver2/jwt/AuthenticationConfig.java
src/main/java/ddwu/project/mdm_ver2/jwt/CustomAccessDeniedHandler.java
src/main/java/ddwu/project/mdm_ver2/jwt/CustomEntryPoint.java
src/main/java/ddwu/project/mdm_ver2/jwt/CustomUserDetails.java
src/main/java/ddwu/project/mdm_ver2/jwt/CustomUserDetailsService.java
src/main/java/ddwu/project/mdm_ver2/jwt/JwtFilter.java
src/main/java/ddwu/project/mdm_ver2/jwt/JwtProvider.java
src/main/java/ddwu/project/mdm_ver2/service/KakaoService.java
src/test/java/ddwu/project/mdm_ver2/jwt/TokenProviderTest.java

- KakaoController API 수정
- Jwt 구현 (jwt 토큰 발급 테스트 추가)
어떤 변경 사항이 있나요?

feat: KakaoController 흐름 수정, Jwt 구현

---

src/main/java/ddwu/project/mdm_ver2/contorller/FavoriteController.java
src/main/java/ddwu/project/mdm_ver2/contorller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/contorller/ViewKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/Favorite.java
src/main/java/ddwu/project/mdm_ver2/jwt/JwtFilter.java
src/main/java/ddwu/project/mdm_ver2/jwt/JwtProvider.java
src/main/java/ddwu/project/mdm_ver2/repository/FavoriteRepository.java
src/main/java/ddwu/project/mdm_ver2/service/FavoriteService.java
src/main/java/ddwu/project/mdm_ver2/service/KakaoService.java

Favorite - User, Favorite - Product DB 연결
FavoriteController parameter annotation 수정
어떤 변경 사항이 있나요?

feat: Favorite 수정

---

src/main/java/ddwu/project/mdm_ver2/contorller/FavoriteController.java
src/main/java/ddwu/project/mdm_ver2/contorller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/Favorite.java
src/main/java/ddwu/project/mdm_ver2/domain/User.java
src/main/java/ddwu/project/mdm_ver2/repository/FavoriteRepository.java
src/main/java/ddwu/project/mdm_ver2/repository/UserRepository.java
src/main/java/ddwu/project/mdm_ver2/service/FavoriteService.java
src/main/java/ddwu/project/mdm_ver2/service/KakaoService.java

카카오 로그인 및 회원가입 로직 수정
회원가입 시 닉네임 입력 과정 삭제 -> 기본 닉네임 부여 후 마이페이지에서 수정 가능
어떤 변경 사항이 있나요?

feat: Kakao 로그인/회원가입 로직 수정

---

src/main/java/ddwu/project/mdm_ver2/contorller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/Favorite.java
src/main/java/ddwu/project/mdm_ver2/repository/FavoriteRepository.java

refactor: Kakao ios 로그인 수정 
어떤 변경 사항이 있나요?

refactor: Kakao ios 로그인 수정 

---

src/main/java/ddwu/project/mdm_ver2/contorller/FavoriteController.java
src/main/java/ddwu/project/mdm_ver2/contorller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/User.java
src/main/java/ddwu/project/mdm_ver2/dto/UserDTO.java
src/main/java/ddwu/project/mdm_ver2/repository/FavoriteRepository.java
src/main/java/ddwu/project/mdm_ver2/service/FavoriteService.java
src/main/java/ddwu/project/mdm_ver2/service/KakaoService.java

Error: jakarta.persistence.EntityExistsException: A different object with the same identifier value was already associated with the session 
-> User Entity, DTO 연결 수정
어떤 변경 사항이 있나요?

refactor: User Entity, DTO 연결 수정

---

src/main/java/ddwu/project/mdm_ver2/contorller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/contorller/SecondHandController.java
src/main/java/ddwu/project/mdm_ver2/domain/SecondHand.java
src/main/java/ddwu/project/mdm_ver2/domain/SecondHandReq.java
src/main/java/ddwu/project/mdm_ver2/dto/SecondHandRequest.java
src/main/java/ddwu/project/mdm_ver2/jwt/JwtProvider.java
src/main/java/ddwu/project/mdm_ver2/repository/SecondHandRepository.java
src/main/java/ddwu/project/mdm_ver2/service/SecondHandService.java
src/test/java/ddwu/project/mdm_ver2/jwt/TokenProviderTest.java

- 중고거래 API 추가 (상품 등록, 상세 정보 조회, 전체 조회 및 정렬, 상품 삭제)
- jwt 토큰 발급 수정 (user_code -> access_token)
어떤 변경 사항이 있나요?

feat: 중고거래 API 추가, jwt 토큰 발급 수정

---

src/main/java/ddwu/project/mdm_ver2/contorller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/Role.java
src/main/java/ddwu/project/mdm_ver2/domain/User.java
src/main/java/ddwu/project/mdm_ver2/dto/UserDTO.java
src/main/java/ddwu/project/mdm_ver2/jwt/AuthenticationConfig.java
src/main/java/ddwu/project/mdm_ver2/jwt/CustomAccessDeniedHandler.java
src/main/java/ddwu/project/mdm_ver2/jwt/CustomEntryPoint.java
src/main/java/ddwu/project/mdm_ver2/jwt/CustomUserDetails.java
src/main/java/ddwu/project/mdm_ver2/jwt/JwtFilter.java
src/main/java/ddwu/project/mdm_ver2/jwt/JwtProvider.java

UserRole enum 추가 및 수정
: ADMIN, USER, GENERAL
어떤 변경 사항이 있나요?

refactor: UserRole enum 수정

---

src/main/java/ddwu/project/mdm_ver2/contorller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/contorller/SecondHandController.java
src/main/java/ddwu/project/mdm_ver2/contorller/SecondHandReqController.java
src/main/java/ddwu/project/mdm_ver2/dto/JwtToken.java
src/main/java/ddwu/project/mdm_ver2/dto/SecondHandReqRequest.java
src/main/java/ddwu/project/mdm_ver2/jwt/AuthenticationConfig.java
src/main/java/ddwu/project/mdm_ver2/jwt/JwtFilter.java
src/main/java/ddwu/project/mdm_ver2/repository/SecondHandReqRepository.java
src/main/java/ddwu/project/mdm_ver2/service/SecondHandReqService.java
src/main/java/ddwu/project/mdm_ver2/service/SecondHandService.java

SecondHand API 추가 및 수정
어떤 변경 사항이 있나요?

refator: SecondHand API 추가 및 수정

---

src/main/java/ddwu/project/mdm_ver2/repository/SecondHandReqRepository.java

SecondHandReqRepository -> JpaRepository<SecondHandReq, Long> 도메인 변경
어떤 변경 사항이 있나요?

refactor: SecondHandReqRepository 오류 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/SecondHandController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/service/UserService.java
src/main/java/ddwu/project/mdm_ver2/global/jwt/AuthenticationConfig.java
src/main/java/ddwu/project/mdm_ver2/global/jwt/JwtFilter.java

refactor: 권한 설정, RestKakaoController 수정
어떤 변경 사항이 있나요?

refactor: 권한 설정, RestKakaoController 수정

---

src/main/java/ddwu/project/mdm_ver2/global/jwt/AuthenticationConfig.java

refactor: 권한 목록 수정
어떤 변경 사항이 있나요?

refactor: 권한 목록 수정

---

src/main/java/ddwu/project/mdm_ver2/global/jwt/JwtProvider.java
src/main/java/ddwu/project/mdm_ver2/global/jwt/oauth/CustomUserDetails.java
src/main/java/ddwu/project/mdm_ver2/global/jwt/oauth/CustomUserDetailsService.java

fix: UserDetailService null 에러 수정
어떤 변경 사항이 있나요?

fix: UserDetailService null 에러 수정

---

src/main/java/ddwu/project/mdm_ver2/global/jwt/JwtProvider.java

fix: UserDetailService NumberFormatException 오류 수정
어떤 변경 사항이 있나요?

fix: UserDetailService 오류 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/user/controller/RestKakaoController.java
src/test/java/ddwu/project/mdm_ver2/jwt/TokenProviderTest.java

refactor: token 수정
어떤 변경 사항이 있나요?

refactor: token 수정

---

src/main/java/ddwu/project/mdm_ver2/global/jwt/JwtFilter.java

refactor: log 수정
어떤 변경 사항이 있나요?

refactor: log 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/product/controller/ProductController.java
src/test/java/ddwu/project/mdm_ver2/jwt/TokenProviderTest.java

refactor: athentication test
어떤 변경 사항이 있나요?

refactor: athentication test

---

src/main/java/ddwu/project/mdm_ver2/domain/user/controller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/ViewKakaoController.java
src/main/java/ddwu/project/mdm_ver2/global/mapping/controller/MappingController.java

refactor: login 화면 전환 (model, view 반환)
어떤 변경 사항이 있나요?

refactor: login 화면 전환 (model, view 반환)

---

src/main/java/ddwu/project/mdm_ver2/domain/cartItem/controller/CartItemController.java
src/main/java/ddwu/project/mdm_ver2/domain/product/controller/ProductController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/SecondHandBidController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/SecondHandController.java
src/main/java/ddwu/project/mdm_ver2/global/exception/CustomResponse.java

> 🎨 improve : api명세 규칙
어떤 변경 사항이 있나요?
add, update, delete, sort

🎨 improve : api명세 규칙

---

src/main/java/ddwu/project/mdm_ver2/domain/favorite/controller/FavoriteController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/ViewKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/dto/UserResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/user/entity/User.java
src/main/java/ddwu/project/mdm_ver2/domain/user/repository/UserRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/user/service/UserService.java
src/main/java/ddwu/project/mdm_ver2/global/jwt/AuthenticationConfig.java
src/main/java/ddwu/project/mdm_ver2/global/jwt/JwtFilter.java
src/main/java/ddwu/project/mdm_ver2/global/jwt/JwtProvider.java
src/main/java/ddwu/project/mdm_ver2/global/jwt/oauth/CustomUserDetails.java
src/main/java/ddwu/project/mdm_ver2/global/jwt/oauth/CustomUserDetailsService.java
src/test/java/ddwu/project/mdm_ver2/jwt/TokenProviderTest.java

refactor: User 변수 이름 수정
어떤 변경 사항이 있나요?

refactor: User 변수 이름 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/cart/controller/CartController.java
src/main/java/ddwu/project/mdm_ver2/domain/cart/service/CartService.java
src/main/java/ddwu/project/mdm_ver2/domain/cartItem/controller/CartItemController.java
src/main/java/ddwu/project/mdm_ver2/domain/cartItem/service/CartItemService.java
src/main/java/ddwu/project/mdm_ver2/domain/favorite/controller/FavoriteController.java
src/main/java/ddwu/project/mdm_ver2/domain/product/controller/ProductController.java
src/main/java/ddwu/project/mdm_ver2/domain/product/service/ProductService.java

> 🎨 improve : 서비스 응답처리
어떤 변경 사항이 있나요?
cart, cartItem , product부분 service예외처리함.

🎨 improve : 서비스 응답처리

---

src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/SecondHandBidController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/SecondHandController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/dto/SecondHandResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/repository/SecondHandBidRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandBidService.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandService.java
src/main/java/ddwu/project/mdm_ver2/domain/user/entity/User.java

- SecondHand API / Entity 수정
어떤 변경 사항이 있나요?

♻️ refactor: SecondHand API / Entity 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/favorite/controller/FavoriteController.java
src/main/java/ddwu/project/mdm_ver2/domain/favorite/repository/FavoriteRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/favorite/service/FavoriteService.java
src/main/java/ddwu/project/mdm_ver2/domain/product/controller/ProductController.java
src/main/java/ddwu/project/mdm_ver2/domain/product/dto/ProductResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/product/service/ProductService.java

-  Favorite-Product API 수정
: 상품 상세 조회 시 사용자의 찜 여부 확인 가능하도록 수정
어떤 변경 사항이 있나요?

♻️ refactor: Favorite-Product API 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/favorite/controller/FavoriteController.java
src/main/java/ddwu/project/mdm_ver2/domain/favorite/entity/Favorite.java
src/main/java/ddwu/project/mdm_ver2/domain/favorite/entity/FavoriteType.java
src/main/java/ddwu/project/mdm_ver2/domain/favorite/repository/FavoriteRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/favorite/service/FavoriteService.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/SecondHandController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/dto/SecondHandResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandService.java

- Favorite-SecondHand API 수정
: 중고 거래 상품 상세 조회 시 사용자의 찜 여부 확인 가능하도록 수정
어떤 변경 사항이 있나요?

♻️ refactor: Favorite-SecondHand API 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/review/controller/ReviewController.java
src/main/java/ddwu/project/mdm_ver2/domain/review/dto/ReviewRequest.java
src/main/java/ddwu/project/mdm_ver2/domain/review/entity/Review.java
src/main/java/ddwu/project/mdm_ver2/domain/review/repository/ReviewRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/review/service/ReviewService.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/ViewKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/service/UserService.java

- 리뷰 API 추가 : 정렬 (최신순, 별점 낮은 순 / 높은 순, 기본순), 추가, 수정, 삭제
- jwt access_token 확인 코드 추가
어떤 변경 사항이 있나요?

✨ feat : 리뷰 API

---

src/main/java/ddwu/project/mdm_ver2/domain/product/dto/ProductResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/product/service/ProductService.java

♻️refactor: Product-Review 연결 및 수정
어떤 변경 사항이 있나요?
: ProductService 상품 상세 조회 부분 수정

[⚙️]♻️refactor: Product-Review 연결 및 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/favorite/controller/FavoriteController.java

🐛fix: favorite api 수정
어떤 변경 사항이 있나요?
: Get -> Post 수정

[⚙️]🐛fix: favorite api 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/product/dto/ProductResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/product/entity/Product.java
src/main/java/ddwu/project/mdm_ver2/domain/product/service/ProductService.java
src/main/java/ddwu/project/mdm_ver2/domain/review/controller/ReviewController.java
src/main/java/ddwu/project/mdm_ver2/domain/review/repository/ReviewRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/review/service/ReviewService.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandBidService.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/RestKakaoController.java

🐛fix: review 기능 추가/수정
어떤 변경 사항이 있나요?
: 사용자가 작성한 reviewList 확인
: review add/delete 시 개수 count

[⚙]🐛fix: review 기능 추가/수정

---

src/main/java/ddwu/project/mdm_ver2/domain/cart/controller/CartApi.java
src/main/java/ddwu/project/mdm_ver2/domain/cart/controller/CartController.java
src/main/java/ddwu/project/mdm_ver2/domain/cart/dto/CartResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/cart/entity/Cart.java
src/main/java/ddwu/project/mdm_ver2/domain/cart/repository/CartRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/cart/service/CartService.java
src/main/java/ddwu/project/mdm_ver2/domain/cartItem/controller/CartItemApi.java
src/main/java/ddwu/project/mdm_ver2/domain/cartItem/controller/CartItemController.java
src/main/java/ddwu/project/mdm_ver2/domain/cartItem/entity/Items.java
src/main/java/ddwu/project/mdm_ver2/domain/cartItem/repository/ItemsRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/cartItem/service/CartItemService.java
src/main/java/ddwu/project/mdm_ver2/domain/category/entity/Category.java
src/main/java/ddwu/project/mdm_ver2/domain/category/repository/CategoryRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/category/service/CategoryService.java

>  장바구니 Swagger 설명 작성
Api를 분리하여 implements시킴.
설명, 성공/실패에 대한 설명 추가
어떤 변경 사항이 있나요?

[⚙️]📝docs: 장바구니 Swagger 설명 작성

---

src/main/java/ddwu/project/mdm_ver2/domain/favorite/repository/FavoriteRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/favorite/service/FavoriteService.java
src/main/java/ddwu/project/mdm_ver2/domain/product/dto/ProductResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/product/entity/Product.java
src/main/java/ddwu/project/mdm_ver2/domain/product/service/ProductService.java
src/main/java/ddwu/project/mdm_ver2/domain/review/controller/ReviewController.java
src/main/java/ddwu/project/mdm_ver2/domain/review/repository/ReviewRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/review/service/ReviewService.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/SecondHandBidController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandBidService.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/RestKakaoController.java

🐛fix: review 평점 계산, SecondHand 수정
어떤 변경 사항이 있나요?
- review 평점 계산, product 연결
- SecondHandBid 사용자 본인이 작성한 요청만 수정 및 삭제 가능 

[⚙]🐛fix: review 평점 계산, SecondHand 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/favorite/controller/FavoriteApi.java
src/main/java/ddwu/project/mdm_ver2/domain/favorite/controller/FavoriteController.java
src/main/java/ddwu/project/mdm_ver2/domain/favorite/service/FavoriteService.java
src/main/java/ddwu/project/mdm_ver2/domain/review/controller/ReviewApi.java
src/main/java/ddwu/project/mdm_ver2/domain/review/controller/ReviewController.java
src/main/java/ddwu/project/mdm_ver2/domain/review/service/ReviewService.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/SecondHandApi.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/SecondHandBidApi.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/SecondHandBidController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/SecondHandController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandBidService.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandService.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/UserApi.java

📝docs: Swagger 설명 작성
- API를 분리하여 Controller에 implements
- 각 API / Parameter에 대한 설명, 실행 응답에 대한 설명 작성
어떤 변경 사항이 있나요?

[⚙️]📝docs: Swagger 설명 작성

---

src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/controller/GroupPurchaseController.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/controller/gp/GroupPurcahseApi.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/controller/gp/GroupPurchaseController.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/controller/gpAdmin/GroupPurchaseAdminApi.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/controller/gpAdmin/GroupPurchaseAdminContorller.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/dto/GroupPurchaseRequest.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/entity/GPStatus.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/entity/GroupPurchase.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/entity/GroupPurchaseParticipant.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/repository/GroupPurchaseParticipantRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/repository/GroupPurchaseRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/service/GroupPurchaseService.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/service/GroupPurchaseStatusUpdater.java
src/main/java/ddwu/project/mdm_ver2/global/config/SwaggerConfig.java
src/main/java/ddwu/project/mdm_ver2/global/exception/ResourceNotFoundException.java
src/main/java/ddwu/project/mdm_ver2/global/jwt/AuthenticationConfig.java

> [⚙️]✨feat: 공동구매API
공동구매API 결제 전까지 개발 완료
swagger token 테스트 가능하게 수정
어떤 변경 사항이 있나요?

[⚙️]✨feat: 공동구매API

---

src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/controller/GroupPurcahseApi.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/controller/GroupPurchaseController.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/controller/gpAdmin/GroupPurchaseAdminApi.java
src/main/java/ddwu/project/mdm_ver2/domain/product/controller/ProductApi.java
src/main/java/ddwu/project/mdm_ver2/domain/product/controller/ProductController.java
src/main/java/ddwu/project/mdm_ver2/domain/product/controller/productAdmin/ProductAdminApi.java
src/main/java/ddwu/project/mdm_ver2/domain/product/controller/productAdmin/ProductAdminController.java
src/main/java/ddwu/project/mdm_ver2/domain/product/dto/ProductResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/product/repository/ProductRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/product/service/ProductService.java

> [⚙️]📝docs: 일반상품 Swagger 설명 작성
최대한 공동구매, 중고거래랑 맞춰서 작성했어요.
어떤 변경 사항이 있나요?

[⚙️]📝docs: 일반상품 Swagger 설명 작성

---

src/main/java/ddwu/project/mdm_ver2/domain/review/controller/ReviewController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/sh/SecondHandApi.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/sh/SecondHandController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/shBid/SecondHandBidApi.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/shBid/SecondHandBidController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/dto/sh/SecondHandRequest.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/dto/sh/SecondHandResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/dto/shBid/SecondHandBidRequest.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandBidService.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandService.java

🐛fix: SecondHandBid 사용자 처리
어떤 변경 사항이 있나요?
: Principal null인 경우 처리

[⚙]🐛fix: SecondHandBid 사용자 처리

---

src/main/java/ddwu/project/mdm_ver2/domain/product/controller/ProductController.java
src/main/java/ddwu/project/mdm_ver2/domain/product/service/ProductService.java
src/main/java/ddwu/project/mdm_ver2/domain/review/controller/ReviewController.java
src/main/java/ddwu/project/mdm_ver2/domain/review/service/ReviewService.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/shBid/SecondHandBidController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandService.java

🐛fix: Product, Review 사용자 처리
어떤 변경 사항이 있나요?
- Principal null인 경우 처리

[⚙]🐛fix: Product, Review 사용자 처리

---

src/main/java/ddwu/project/mdm_ver2/domain/user/controller/UserApi.java

📝docs: 사용자 Swagger 설명 작성
어떤 변경 사항이 있나요?
- 카카오 로그인 API 설명 추가

[⚙️]📝docs: 사용자 Swagger 설명 작성

---

src/main/java/ddwu/project/mdm_ver2/domain/mypage/controller/MyPageApi.java
src/main/java/ddwu/project/mdm_ver2/domain/mypage/controller/MyPageController.java
src/main/java/ddwu/project/mdm_ver2/domain/mypage/service/MyPageService.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/UserApi.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/ViewKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/service/UserService.java
src/main/java/ddwu/project/mdm_ver2/global/config/RedisRepositoryConfig.java
src/main/java/ddwu/project/mdm_ver2/global/jwt/AuthenticationConfig.java
src/main/java/ddwu/project/mdm_ver2/global/jwt/JwtFilter.java
src/main/java/ddwu/project/mdm_ver2/global/jwt/JwtProvider.java
src/main/java/ddwu/project/mdm_ver2/global/redis/RedisUtil.java

✨feat: 로그아웃, 토큰 재발급 API
- 카카오 계정과 함께 로그아웃 
-> 로그아웃 시 Jwt Access Token Redis에 logout 토큰으로 등록
- Jwt Access Token 만료 시 Jwt Refresh Token을 통해 재발급
- Jwt Refresh Token도 만료되었을 경우 재로그인
어떤 변경 사항이 있나요?

[⚙️]✨feat: 로그아웃, 토큰 재발급 API

---

src/main/java/ddwu/project/mdm_ver2/domain/user/controller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/UserApi.java
src/main/java/ddwu/project/mdm_ver2/domain/user/service/UserService.java

📝docs: 사용자 Swagger 설명 추가
어떤 변경 사항이 있나요?
- 로그아웃, 토큰 재발급 API 설명 추가

[⚙️]📝docs: 사용자 Swagger 설명 추가

---

src/main/java/ddwu/project/mdm_ver2/domain/user/controller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/UserApi.java
src/main/java/ddwu/project/mdm_ver2/domain/user/service/UserService.java

🐛fix: 카카오 계정과 함께 로그아웃
어떤 변경 사항이 있나요?
- 로그아웃 성공 시 응답코드 302

[⚙]🐛fix: 로그아웃

---

src/main/java/ddwu/project/mdm_ver2/domain/user/controller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/UserApi.java
src/main/java/ddwu/project/mdm_ver2/domain/user/service/UserService.java
src/main/java/ddwu/project/mdm_ver2/global/jwt/JwtProvider.java
src/test/java/ddwu/project/mdm_ver2/jwt/TokenProviderTest.java

🐛fix: 회원 탈퇴/카카오 연결 끊기
- 사용자 DB 삭제, Redis 토큰 삭제, 카카오 연결 끊기 
어떤 변경 사항이 있나요?
: 사용자 Swagger > 회원 탈퇴 설명 추가

[⚙]🐛fix: 회원 탈퇴/카카오 연결 끊기

---

src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/shBid/SecondHandBidApi.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/shBid/SecondHandBidController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/dto/sh/SecondHandResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/dto/shBid/SecondHandBidDto.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/entity/SecondHand.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandBidService.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandService.java

🐛fix: SecondHandBid Response 처리 수정
어떤 변경 사항이 있나요?
: 중고거래 상품 상세 정보 요청 시 중고거래 요청 리스트 부분 관련 response body 형식 수정

[⚙]🐛fix: SecondHandBid Response 처리 수정

---

src/main/java/ddwu/project/mdm_ver2/global/jwt/AuthenticationConfig.java

🐛fix: API 권한 부여
- 사용자 권한에 해당하는 API 구분
어떤 변경 사항이 있나요?

[⚙]🐛fix: API 권한 부여

---

src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/controller/GroupPurcahseApi.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/controller/GroupPurchaseController.java
src/main/java/ddwu/project/mdm_ver2/domain/mypage/controller/MyPageApi.java
src/main/java/ddwu/project/mdm_ver2/domain/mypage/controller/MyPageController.java
src/main/java/ddwu/project/mdm_ver2/domain/mypage/dto/AddressRequest.java
src/main/java/ddwu/project/mdm_ver2/domain/mypage/service/MyPageService.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/UserApi.java

✨feat: 마이페이지 API 추가
어떤 변경 사항이 있나요?
: 주소 / 닉네임 업데이트, 공동구매 상품 참여 리스트 조회 기능

[⚙]✨feat: 마이페이지 API 추가

---

src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/sh/SecondHandApi.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/sh/SecondHandController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/shBid/SecondHandBidApi.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/shBid/SecondHandBidController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/dto/sh/SecondHandRequest.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/dto/sh/SecondHandResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/dto/shBid/SecondHandBidRequest.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/dto/shBid/SecondHandBidResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandBidService.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandService.java

🐛fix: SecondHandBid Request 수정
어떤 변경 사항이 있나요?
: request에 요청 id, 해당 사용자 id 삭제
: 중고거래 요청 request, response 분리

[⚙]🐛fix: SecondHandBid Request 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/favorite/entity/Favorite.java
src/main/java/ddwu/project/mdm_ver2/domain/favorite/service/FavoriteService.java

Resolves: #95 
어떤 변경 사항이 있나요?
: 찜 기능 수정 (공동 구매 상품  찜 가능하도록 추가)

[⚙]🐛fix: 공동 구매 상품 찜 추가

---

src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/controller/GroupPurcahseApi.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/service/GroupPurchaseService.java

Resolves: #97 
어떤 변경 사항이 있나요?
: 공동구매 참여 시 현재 수량에 반영, 최대 구매 수량 초과 시 구매 제한

[⚙]🐛fix: 공동구매 현재 수량 변경/구매 수량 제한

---

src/main/java/ddwu/project/mdm_ver2/domain/user/controller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/UserApi.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/ViewKakaoController.java
src/main/java/ddwu/project/mdm_ver2/global/mapping/controller/MappingController.java
src/main/webapp/WEB-INF/views/includes/header.jsp
src/main/webapp/WEB-INF/views/main.jsp
src/main/webapp/WEB-INF/views/product.jsp

[🌸]✨feat:토큰 헤더 전달 및 상품 리스트 출력

---

build.gradle

[⚙️]♻️refactor: build.gradle dependencies 정리

---

src/main/java/ddwu/project/mdm_ver2/domain/user/controller/RestKakaoController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/controller/UserApi.java
src/main/java/ddwu/project/mdm_ver2/global/mapping/controller/MappingController.java

Resolves: #102 
어떤 변경 사항이 있나요?
: Json 형태의 데이터 반환 대신 view 반환하도록 수정

[⚙]🐛fix: 로그인 완료 화면 처리

---

src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/service/GroupPurchaseService.java
src/main/java/ddwu/project/mdm_ver2/domain/product/dto/ProductResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/product/entity/Product.java
src/main/java/ddwu/project/mdm_ver2/domain/product/service/ProductService.java
src/main/java/ddwu/project/mdm_ver2/domain/review/repository/ReviewRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/review/service/ReviewService.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/entity/SecondHand.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/repository/SecondHandBidRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandBidService.java
src/main/java/ddwu/project/mdm_ver2/domain/user/service/UserService.java

Resolves: #104 
어떤 변경 사항이 있나요?
: 회원 데이터 일괄 삭제 전 사용자가 작성한 리뷰, 중고거래 요청, 참여 공동구매 데이터를 찾아 삭제
-> 해당 데이터와 관련된 데이터들 변동 사항 반영 (개수 감소, 평점 계산)

[⚙]🐛fix: 회원 탈퇴 데이터 반영

---

src/main/java/ddwu/project/mdm_ver2/domain/cartItem/entity/Items.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/controller/GroupPurcahseApi.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/entity/GroupPurchaseParticipant.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/service/GroupPurchaseService.java
src/main/java/ddwu/project/mdm_ver2/domain/mypage/controller/MyPageApi.java
src/main/java/ddwu/project/mdm_ver2/domain/mypage/controller/MyPageController.java
src/main/java/ddwu/project/mdm_ver2/domain/order/controller/OrderApi.java
src/main/java/ddwu/project/mdm_ver2/domain/order/controller/OrderController.java
src/main/java/ddwu/project/mdm_ver2/domain/order/dto/OrderDto.java
src/main/java/ddwu/project/mdm_ver2/domain/order/entity/Order.java
src/main/java/ddwu/project/mdm_ver2/domain/order/repository/OrderRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/order/service/OrderService.java

Resolves: #92 
어떤 변경 사항이 있나요?
- order 구현
- /mypage/gp return에 purchasedQty 구매한 수량 없어서 수정함.
- Api @ApiResponses(value = {형태로 수정

[⚙️]✨feat: Order 구현

---

src/main/java/ddwu/project/mdm_ver2/domain/cartItem/controller/CartItemApi.java
src/main/java/ddwu/project/mdm_ver2/domain/order/controller/OrderApi.java
src/main/java/ddwu/project/mdm_ver2/domain/order/controller/OrderController.java
src/main/java/ddwu/project/mdm_ver2/domain/order/service/OrderService.java

Resolves: #107 
어떤 변경 사항이 있나요?

[⚙️]♻️refactor:order 정리

---

src/main/java/ddwu/project/mdm_ver2/global/mapping/controller/MappingController.java

Resolves: #109 
어떤 변경 사항이 있나요?

[⚙]🐛fix: jsp view 연결

---

src/main/java/ddwu/project/mdm_ver2/domain/product/entity/Product.java
src/main/java/ddwu/project/mdm_ver2/domain/product/service/ProductService.java

Resolves: #113 
어떤 변경 사항이 있나요?
: 상품 등록 시 리뷰 개수 초기값 -> 0으로 등록

[⚙]🐛fix: 상품 리뷰 개수 초기값 설정

---

src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/sh/SecondHandApi.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/sh/SecondHandController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandService.java

Resolves: #115 
어떤 변경 사항이 있나요?
: 규칙에 맞게 검색 시 예외 처리

[⚙]🐛fix: 중고거래 검색 응답 처리 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandService.java

Resolves: #117 
어떤 변경 사항이 있나요?
: 중고 거래 상품 등록 시 요청 개수 초기값 -> 0으로 등록

[⚙]🐛fix: 중고 거래 요청 개수 초기값 설정

---

src/main/webapp/WEB-INF/views/mypage.jsp

Resolves: #127 
어떤 변경 사항이 있나요?

[🌸]🐛fix: 마이페이지 연결

---

src/main/webapp/WEB-INF/views/mypage.jsp

Revert "[🌸]🐛fix: 마이페이지 연결"

---

src/main/java/ddwu/project/mdm_ver2/global/mapping/controller/MappingController.java

Resolves: #131 
어떤 변경 사항이 있나요?
: Model 삭제, view만 return

[⚙]🐛fix: MappingController 수정

---

src/main/java/ddwu/project/mdm_ver2/global/mapping/controller/MappingController.java

🐛fix: 경로 이름 수정
어떤 변경 사항이 있나요?
: MappingController > addSecondhand 경로 이름 수정

[⚙]🐛fix: 경로 이름 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/shBid/SecondHandBidApi.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/shBid/SecondHandBidController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/dto/shBid/SecondHandBidResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandBidService.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandService.java

Resolves: #136 
어떤 변경 사항이 있나요?
: 현재 사용자가 요청 수정, 삭제할 수 있는지 구분

[⚙]🐛fix: SecondHandBid 사용자 구분

---

src/main/java/ddwu/project/mdm_ver2/domain/secondhand/dto/sh/SecondHandResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/dto/shBid/SecondHandBidResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandBidService.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandService.java

Resolves: #138 
어떤 변경 사항이 있나요?
: 응답에 요청 id 추가

[⚙]🐛fix: SecondHandBid 응답 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/product/controller/ProductController.java
src/main/java/ddwu/project/mdm_ver2/domain/product/service/ProductService.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/sh/SecondHandController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/shBid/SecondHandBidController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandBidService.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandService.java

Resolves: #140 
어떤 변경 사항이 있나요?
: 정렬 defaultValue 최신순으로 처리

[⚙]🐛fix: 정렬 기본값 처리

---

src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/controller/GroupPurcahseApi.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/controller/GroupPurchaseController.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/dto/GroupPurchaseResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/repository/GroupPurchaseParticipantRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/service/GroupPurchaseService.java

Resolves: #142 
어떤 변경 사항이 있나요?
: 특정 공동구매 상품 조회 시 응답 형식 수정 (참여자 전체 리스트 전달 -> 참여자 수만 전달)
: 참여자 없어도 조회 가능
: 공동구매 Swagger 수정

[⚙]🐛fix: 공동구매 상품 조회 응답 수정

---

src/main/webapp/WEB-INF/views/grouppurchaseDetails.jsp

Resolves: #144 
어떤 변경 사항이 있나요?
: 공동구매 상품 상세 페이지 연결 및 참여하기 기능 구현

[🌸]✨feat: 공동구매 상세 페이지 연결

---

src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/sh/SecondHandApi.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/sh/SecondHandController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandService.java

Resolves: #148 
어떤 변경 사항이 있나요?
: 사용자 본인이 올린 상품인 경우에만 거래 가능
: 중고거래 Swagger 수정

[⚙]🐛fix: 중고 상품 거래 권한 수정

---

src/main/webapp/WEB-INF/views/addSecondhand.jsp

Resolves: #150 
어떤 변경 사항이 있나요?

[🌸]✨feat: 중고 상품 등록 연결

---

src/main/webapp/WEB-INF/views/secondhandDetails.jsp

Resolves: #152 
어떤 변경 사항이 있나요?

[🌸]✨feat: 중고 거래 요청 연결

---

src/main/java/ddwu/project/mdm_ver2/global/mapping/controller/MappingController.java

Resolves: #156 
어떤 변경 사항이 있나요?

[⚙]✨feat: 마이페이지 mapping 추가

---

src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/sh/SecondHandApi.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/sh/SecondHandController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/dto/sh/SecondHandResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/dto/shBid/SecondHandBidResponse.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/entity/SecondHand.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/entity/SecondHandBid.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandBidService.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandService.java
src/main/java/ddwu/project/mdm_ver2/global/mapping/controller/MappingController.java

Resolves: #159 
어떤 변경 사항이 있나요?

[⚙]🐛fix: SecondHand 거래 상태 처리

---

src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandBidService.java

Resolves: #162 
어떤 변경 사항이 있나요?

[⚙]🐛fix: SecondHandBid 등록 수정

---

src/main/webapp/WEB-INF/views/secondhandDetails.jsp

Resolves: #168 
어떤 변경 사항이 있나요?

[🌸]✨feat: 중고 거래 연결

---

src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/service/GroupPurchaseService.java

날짜가 수정되면 함께 수정되도록 + 상태 수정에 ONGOING도 추가
Resolves: #170 
어떤 변경 사항이 있나요?

[⚙️]🐛fix:공동구매 날짜 수정 status 반영

---

src/main/java/ddwu/project/mdm_ver2/domain/user/controller/KakaoController.java

Resolves: #172 
어떤 변경 사항이 있나요?

[⚙]🐛fix: 로그아웃 HTTP Method 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/review/service/ReviewService.java

Resolves: #174 
어떤 변경 사항이 있나요?

[⚙]🐛fix: 리뷰 작성 제한

---

src/main/webapp/WEB-INF/views/productDetails.jsp

Resolves: #176 
어떤 변경 사항이 있나요?

[🌸]🐛fix: 리뷰 삭제/수정 메세지창 추가

---

src/main/java/ddwu/project/mdm_ver2/domain/cart/service/CartService.java
src/main/java/ddwu/project/mdm_ver2/global/exception/CustomResponse.java

[⚙️]🐛fix:장바구니 조회 응답 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/order/controller/OrderApi.java
src/main/java/ddwu/project/mdm_ver2/domain/order/controller/OrderController.java
src/main/java/ddwu/project/mdm_ver2/domain/order/entity/Order.java
src/main/java/ddwu/project/mdm_ver2/domain/order/repository/OrderRepository.java
src/main/java/ddwu/project/mdm_ver2/domain/order/service/OrderService.java

Resolves: #178 
어떤 변경 사항이 있나요?

[⚙️]✨feat:Order 일반상품 바로구매

---

src/main/webapp/WEB-INF/views/mypage.jsp

Resolves: #193 
어떤 변경 사항이 있나요?

[🌸]🐛fix: 닉네임 변경 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/controller/GroupPurcahseApi.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/controller/GroupPurchaseController.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/service/GroupPurchaseService.java
src/main/java/ddwu/project/mdm_ver2/domain/order/controller/OrderApi.java
src/main/java/ddwu/project/mdm_ver2/domain/order/controller/OrderController.java
src/main/java/ddwu/project/mdm_ver2/domain/order/dto/OrderAddrRequest.java
src/main/java/ddwu/project/mdm_ver2/domain/order/dto/OrderCartRequest.java
src/main/java/ddwu/project/mdm_ver2/domain/order/entity/Order.java
src/main/java/ddwu/project/mdm_ver2/domain/order/service/OrderService.java

[⚙]🐛fix:주문자 정보 한 번에 호출

---

src/main/java/ddwu/project/mdm_ver2/domain/favorite/controller/FavoriteApi.java
src/main/java/ddwu/project/mdm_ver2/domain/favorite/controller/FavoriteController.java
src/main/java/ddwu/project/mdm_ver2/domain/favorite/service/FavoriteService.java
src/main/java/ddwu/project/mdm_ver2/domain/mypage/controller/MyPageApi.java
src/main/java/ddwu/project/mdm_ver2/domain/mypage/controller/MyPageController.java
src/main/java/ddwu/project/mdm_ver2/domain/mypage/service/MyPageService.java
src/main/java/ddwu/project/mdm_ver2/domain/review/controller/ReviewApi.java
src/main/java/ddwu/project/mdm_ver2/domain/review/controller/ReviewController.java
src/main/java/ddwu/project/mdm_ver2/domain/review/service/ReviewService.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/sh/SecondHandApi.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/sh/SecondHandController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/shBid/SecondHandBidApi.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/shBid/SecondHandBidController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandBidService.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandService.java
src/main/java/ddwu/project/mdm_ver2/domain/user/service/UserService.java

Resolves: #198 
어떤 변경 사항이 있나요?

[⚙]♻️refactor: 등록, 수정, 삭제 응답 처리 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/sh/SecondHandApi.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/controller/sh/SecondHandController.java
src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandService.java

Resolves: #200 
어떤 변경 사항이 있나요?

[⚙]🐛fix: 중고거래 등록 응답 처리 수정

---

src/main/webapp/WEB-INF/views/addSecondhand.jsp

Resolves: #202 
어떤 변경 사항이 있나요?

[🌸]🐛fix: 중고거래 등록 후 화면 이동 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/secondhand/service/SecondHandService.java

Resolves: #204 
어떤 변경 사항이 있나요?

[⚙]🐛fix: 중고거래 상품 삭제 오류 수정

---

src/main/webapp/WEB-INF/views/mypage.jsp

Resolves: #210 
어떤 변경 사항이 있나요?

[🌸]🐛fix: 수정/삭제 완료 후 알림창

---

src/main/java/ddwu/project/mdm_ver2/global/mapping/controller/MappingController.java

Resolves: #212 
어떤 변경 사항이 있나요?

[⚙]✨feat: 주문 완료 연결 추가

---

src/main/webapp/WEB-INF/views/order.jsp
src/main/webapp/WEB-INF/views/order_finish.jsp

Resolves: #212 
어떤 변경 사항이 있나요?
: 사용자 / 배송지 미입력 시 주문하기 제한

[🌸]✨feat: 주문 완료 화면 추가

---

src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/controller/GroupPurcahseApi.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/controller/GroupPurchaseController.java
src/main/java/ddwu/project/mdm_ver2/domain/grouppurchase/service/GroupPurchaseService.java

Resolves: #215 
어떤 변경 사항이 있나요?

[⚙]🐛fix: API 응답 형식 수정

---

src/main/java/ddwu/project/mdm_ver2/domain/user/controller/GeneralController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/dto/GeneralRequest.java
src/main/java/ddwu/project/mdm_ver2/domain/user/entity/User.java
src/main/java/ddwu/project/mdm_ver2/domain/user/service/UserService.java
src/main/java/ddwu/project/mdm_ver2/global/mapping/controller/MappingController.java
src/main/webapp/WEB-INF/views/login.jsp

Resolves: #217 
어떤 변경 사항이 있나요?

⚙️]✨feat:일반 로그인

---

src/main/java/ddwu/project/mdm_ver2/domain/user/controller/GeneralController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/service/UserService.java
src/main/java/ddwu/project/mdm_ver2/global/mapping/controller/MappingController.java

Resolves: #219 
어떤 변경 사항이 있나요?

[⚙]🐛fix: 일반 회원가입/로그인 수정

---

src/main/webapp/WEB-INF/views/join.jsp
src/main/webapp/WEB-INF/views/login.jsp

일반 회원가입 / 로그인 호출 url 수정
어떤 변경 사항이 있나요?

[🌸]🐛fix: 일반 회원가입/로그인 url 수정

---

src/main/webapp/WEB-INF/views/login.jsp

확인용 alert 코드 삭제
어떤 변경 사항이 있나요?

[🌸]🙈chore: 확인용 alert 코드 삭제

---

src/main/java/ddwu/project/mdm_ver2/domain/user/controller/GeneralController.java
src/main/java/ddwu/project/mdm_ver2/domain/user/service/UserService.java

Resolves: #223 
어떤 변경 사항이 있나요?

[⚙]✨feat: 일반 가입 id/기본 닉네임 통일

---

src/main/java/ddwu/project/mdm_ver2/domain/user/entity/User.java
src/main/java/ddwu/project/mdm_ver2/domain/user/service/UserService.java
src/main/java/ddwu/project/mdm_ver2/global/jwt/AuthenticationConfig.java

[⚙️]🐛fix:일반 가입 제약조건&암호화

---

src/main/java/ddwu/project/mdm_ver2/global/jwt/AuthenticationConfig.java

Resolves: #229 
어떤 변경 사항이 있나요?
- [] 변경 사항에 대한 테스트를 했습니다.(버그 수정/기능에 대한 테스트).

[⚙]🐛fix: 관리자 권한 설정
